# Generated by Django 5.1.2 on 2024-10-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активно'),
        ),
    ]
